[package]
name = "reddit"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bytes = "1.0.0"
http = "0.2.2"
hyper = "0.13.9"
hyper-tls = "0.4.3"
serde = { version = "1.0.118", features = [ "derive" ] }
serde_json = "1.0.60"
thiserror = "1.0.22"
url = { version = "2.2.0", features = [ "serde" ] }

[dev-dependencies]
tokio = { version = "0.2.22", features = [ "macros" ] }
